services:
  - type: web
    name: pixelplates-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: pixelplates-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: pixelplates-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: pixelplates-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pixelplates-db
          property: password
      - key: TWILIO_SID
        value: AC6a566adda0fba8004ba72271976f61a6
      - key: TWILIO_AUTH_TOKEN
        value: 480e563b20ae39c7b431737315914a94
      - key: TWILIO_NUMBER
        value: +19714022819
